stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# Define the test stage
test:
  stage: test
  image: alpine:latest
  script:
    - apk add --no-cache curl
    - curl -s http://$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA | grep "Hello world!"

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - master
  script:
    - echo "Deploying hello world application to k8s"
